# Generates a service Dockerfile from the canonical template used by all 10
# microservices in this monorepo. Run from the repo root:
#
#   pwsh scripts/generate-service-dockerfile.ps1 -Service auth-service
#
# Overwrites services/<service>/Dockerfile. The content is parameterized on
# the service name, port, and whether it owns a Prisma schema (most do).
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$Service,
    [int]$Port = 0,
    [switch]$NoPrisma
)

$root = Resolve-Path "$PSScriptRoot/.."
$scaffold = @"
# syntax=docker/dockerfile:1.7
# =============================================================================
# $Service — generated by scripts/generate-service-dockerfile.ps1
# Layer ordering maximises BuildKit cache hits:
#   1. Workspace manifests (rarely change)  →  install layer cached
#   2. Shared package source (occasionally)  →  shared build cached
#   3. Service source (often)                →  tsc layer cached per-change
# =============================================================================

FROM node:24-alpine AS builder

RUN apk add --no-cache openssl
RUN npm install -g pnpm@10

WORKDIR /app

# 1) Workspace manifests
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .pnpmrc tsconfig.base.json ./

# 2) Shared package sources
COPY packages/shared-types/        ./packages/shared-types/
COPY packages/shared-utils/        ./packages/shared-utils/
COPY packages/shared-events/       ./packages/shared-events/
COPY packages/shared-middleware/   ./packages/shared-middleware/

# 3) THIS service's source (last so it busts only the tsc cache)
COPY services/$Service/ ./services/$Service/

# pnpm install: skipped on rebuild unless a manifest / shared source changes.
RUN --mount=type=cache,id=pnpm-cache,target=/root/.pnpm-store `
    pnpm install --frozen-lockfile
"@

if (-not $NoPrisma) {
    $scaffold += @"


# Generate the Prisma client for THIS service only.
RUN pnpm -C services/$Service exec prisma generate
"@
}

$scaffold += @"


# Build only this service + its needed workspace deps.
RUN pnpm --filter @freeshop/$Service... run build

# ============================================================================
# Production stage
# ============================================================================
FROM node:24-alpine AS production

RUN apk add --no-cache openssl

WORKDIR /app

# Workspace + shared package artifacts
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/packages ./packages
"@

if (-not $NoPrisma) {
    $scaffold += @"
COPY --from=builder /app/services/$Service/package.json   ./services/$Service/
COPY --from=builder /app/services/$Service/prisma.config.ts ./services/$Service/
COPY --from=builder /app/services/$Service/generated      ./services/$Service/generated
COPY --from=builder /app/services/$Service/prisma         ./services/$Service/prisma
"@
} else {
    $scaffold += @"
COPY --from=builder /app/services/$Service/package.json ./services/$Service/
"@
}

$scaffold += @"
COPY --from=builder /app/services/$Service/dist ./services/$Service/dist

WORKDIR /app/services/$Service

EXPOSE $Port

# Run app directly; migrations should be executed by CI/k8s Job before rollout
CMD ["node", "dist/src/index.js"]
"@

$out = Join-Path $root "services/$Service/Dockerfile"
Set-Content -Path $out -Value $scaffold -Encoding utf8
Write-Host "Wrote $out"
